name: On Website Deploy
on:
  push:
    # (1)
    branches:
      - "main"
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest
    # (2)
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🌍 Enable Web
        run: flutter config --enable-web

      - name: 📦 Get packages
        run: flutter pub get

      - name: 🏭 Build Web Application
        run: flutter build web --release

      # (3)
      - name: Make copy of artifacts
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
          bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"

      # (4)
      - name: Commit and Push changes
        env:
          GH_PAT: ${{ secrets.FLUTTER }}
        run: |
          git config --global user.name "Yexzari"
          git config --global user.email "20203tn141@utez.edu.mx"
          git add .
          git commit -m "Commit the artifacts"
          git push https://Yexzari:${{ secrets.FLUTTER }}@github.com/Yexzari/CRUDFlutter.git
